# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# Enable C++ support
language: cpp
# Get dependencies
before_update:
   - sudo apt update -qy
   - sudo apt install i2c-tools -qy
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - cd build
  - cmake .. && make
